### ISSUE TITLE
no ggplot2 in docker 

### ISSUE THREAD

**Issue by sridhar0605** [guigolab/ggsashimi#1]
hello team,

This is a great tool.

I am not sure why when I pull you docker image i see this error 

Using default tag: latest
latest: Pulling from guigolab/ggsashimi
Digest: sha256:eab7ae5fa4ae2aadb8fc20e507bda59acb9bf78c12013e8384be2302fbb57f3c
Status: Image is up to date for guigolab/ggsashimi:latest
Error in library(ggplot2) : there is no package called 'ggplot2'
Execution halted

Any help?

Thanks. 

Sid

**Comment by emi80** [comment]
HI @sridhar0605,

thanks for your positive comment and for reporting this issue. 

I just updated the Docker image and pushed it to the Docker Hub. It should work now.

Best,
Emilio

**Comment by sridhar0605** [comment]
He @emi80 

Thank you for the fix, when using Homo_sapiens.GRCh37.75.gtf as reference from ensembl

I see this error

Using default tag: latest
latest: Pulling from guigolab/ggsashimi
915665fee719: Pull complete 
1a0814f59c8e: Pull complete 
b3b71680ed5d: Pull complete 
1c3c8afa6ada: Pull complete 
2fbeb903a5b4: Pull complete 
Digest: sha256:82590f821978568e948ad4861ce009fcb26e7543263bea9d7b78c17667f8d675
Status: Downloaded newer image for guigolab/ggsashimi:latest
Traceback (most recent call last):
  File "/sashimi-plot.py", line 592, in <module>
    transcripts, exons = read_gtf(args.gtf, args.coordinates)
  File "/sashimi-plot.py", line 278, in read_gtf
    transcript_id = d["transcript_id"]
KeyError: 'transcript_id'

**Comment by emi80** [comment]
Moved last problem to its own issue since it's not related to this.
