### ISSUE TITLE
Shrinkage of introns leads to wrong coordinates in x-axis

### ISSUE THREAD

**Issue by dgarrimar** [guigolab/ggsashimi#13]
When using the option `--shrink` it may happen that coordinates shown do not match exactly the actual ones in the genome

**Comment by komalsrathi** [comment]
Hi - is there a work around for this? When plotting a large region with `--shrink`, the coordinates do not match with the genome and the coverage histogram does not align with the exon blocks on the x-axis.

**Comment by dgarrimar** [comment]
We are working to try to fix this asap
