### ISSUE TITLE
Histogram smoothing possible?

### ISSUE THREAD

**Issue by lukedow** [guigolab/ggsashimi#15]
Hi

I pulled ggsashimi from DockerHub and am trying to smooth the histograms with "--smooth" but the argument is not recognized. In the GitHub code it looks to be commented out. Is there another argument or is smoothing not possible, currently?

Thanks, Luke

**Comment by dgarrimar** [comment]
Hi @lukedow, we considered the `--smooth` option at first, but then no further develpment was done, as we thought that for most cases, the histogram would not require any smoothing: in average regions it would make no difference, and in very short regions the user is probably interested in each individual base. Is there any particular case for which you would be interested in smoothing? Actually it was your issue what reminded me that the commented line was there, and as it may confuse some users, we will remove it.

**Comment by lukedow** [comment]
Thanks for the quick reply. In this particular case we have a heterozygous large deletion taking out half of a large exon, and would like to show this visually, but the plots look quite jagged and I think it would be easier to interpret if it was smoothed or binned in some way. Is it possible? Or is there another function / tool that would help? 
<img width="403" alt="screenshot 2019-01-30 06 46 58" src="https://user-images.githubusercontent.com/47162932/51988970-dd4d5480-245a-11e9-8070-3962c4f7e514.png">

**Comment by dgarrimar** [comment]
Hi @lukedow, in principle it is not possible with the current implementation, as we aimed to show always the data as it is; still I think that what you want to show can be seen relatively clear. You can try to show a larger region so that the bins look more collapsed, and play with the `--shrink` option.
