### ISSUE TITLE
Integration in Galaxy

### ISSUE THREAD

**Issue by bellenger-l** [guigolab/ggsashimi#16]
Hello,

I really like your tool and I find it very useful. I wonder if you already thought about wrapping your ggsashimi into Galaxy ? 
I am currently working in the bioinformatics plateform ARTbio (see our github [here](https://github.com/ARTbio) ) and we work a lot with Galaxy by developping the framework but also different tools and wrapping them.

Would you agree to allow our platform to create the galaxy wrapper ? This would be an opportunity to provide a sashimi plot generator to Galaxy users. 

Best,
Lea

**Comment by dgarrimar** [comment]
Dear Lea,

It's great that you find our tool useful. Sure, we will be more than happy if you guys want to work on a Galaxy wrapper for ggsashimi. Please don't hesitate to contact us in case you need any help or further info.

thank you!

Diego

**Comment by dgarrimar** [comment]
Hi @bellenger-l, did you go on with this idea?

**Comment by bellenger-l** [comment]
Hello @dgarrimar ! Sorry I completely forgot to mention it ! 
I finish to wrap your tool into Galaxy : here is our development repository : https://github.com/ARTbio/tools-artbio/tree/master/tools/sashimi_plot
I put your publication in citation. You can now also find your tool on the [Galaxy toolshed](https://toolshed.g2.bx.psu.edu)

**Comment by dgarrimar** [comment]
Wow! that's really great Lea, thanks a lot!

**Comment by bellenger-l** [comment]
My pleasure ! 
For info : https://toolshed.g2.bx.psu.edu/view/artbio/sashimi_plot/64aa67b5099f

Best,
Lea
