### ISSUE TITLE
Error: unexpected symbol in "        color_list = list(ConAc_A2-11D.sorted"

### ISSUE THREAD

**Issue by sneha100895** [guigolab/ggsashimi#19]
Hi, 

I get the following error when using sashimi-plot.py

This is my code 
`python sashimi-plot.py -b /project/uml_frederic_chain/Daphnia/index/ConAc_A2-11D.sorted.bam -c DAPPUscaffold_67:640865-642375 -g /project/uml_frederic_chain/Daphnia/Daphnia_pulex.V1.0.41.exons.gtf --shrink `

Could you please help me out in resolving this.

**Comment by dgarrimar** [comment]
Hi @sneha100895,

In the past I remember that the dash symbol in the file name was giving some problems. Can you try renaming your BAM? If that is the case, we will try to fix the problem in the code. 

Best,

**Comment by sneha100895** [comment]
> Hi @sneha100895,
> 
> In the past I remember that the dash symbol in the file name was giving some problems. Can you try renaming your BAM? If that is the case, we will try to fix the problem in the code.
> 
> Best,

**Comment by sneha100895** [comment]
Hi,

Renaming the BAM file worked!

Thank you.

**Comment by TOTTW** [comment]
Hi,

I also have the same question:

> sashimi-plot.py -g Homo_sapiens.GRCh38.94.gtf -b 1119TCXSE141816.bam -c  chr9:128936582-128940709 -o 1119_TCX.SE_141816

Error: unexpected symbol in "        color_list = list(1119TCXSE141816"
Execution halted

Could you please help me?

Thank you!

**Comment by TOTTW** [comment]
Sorry to bother, I find the answer in #26.  The bam file name should not start with a number.
