### ISSUE TITLE
What's the difference between the flag -S OUT_STRAND and -s STRAND?

### ISSUE THREAD

**Issue by shannjiang** [guigolab/ggsashimi#24]
Hi,

I am using the ggsashimi to generate sashimi plots for my results. The alternative splicing events I am interested in are located in either + or - strand. I checked the help info of ggsashimi, and the -S OUT_STRAND and -s STRAND are the two flags I can set to focus on only one strand. 

But I am not sure how to correctly set the two flags. For my understanding, if the alternative splicing event I am interested in is located in - strand, -s was set to ANTISENSE. How about -S? Should I set it to minus which is compatible to -s flag? What does the out strand mean?

thanks,

Shan

**Comment by dgarrimar** [comment]
HI @shannjiang, the ```-s``` flag refers to the strandness of the RNA-seq protocol. If you just want to show the reads mapping to one of the strands (provided that the RNA-seq protocol is stranded), you can do it using ```-S```. Does it make sense? Maybe we can make the help message clearer

**Comment by shannjiang** [comment]
Hi@dgarrimar, thanks for your reply. But there are two flags, -s and -S as shown in the ggsashimi plot help message, -s is strand and -S is out_strand. I understood -s refers to the strandness of the RNA-seq. But how about the capitalized -S flag? What is out_strand?

**Comment by dgarrimar** [comment]
As I said in the previous message, capital ```-S``` refers to whether you want to show in the plot only the plus or the minus strand. Imagine you have a stranded protocol (e.j. you set ```-s``` to ```MATE1_SENSE```), but you are looking at an exon inclusion event within a gene in the minus strand, which overlaps an antisense lncRNA. If you just want to see the reads corresponding to the minus strand, you should set ```-S minus```. Is it clearer now?

**Comment by shannjiang** [comment]
Thanks! I fully understood now.
