### ISSUE TITLE
coordinate flag do not match with coordinate on x-axis of generated graph if using --shrink flag

### ISSUE THREAD

**Issue by shannjiang** [guigolab/ggsashimi#25]
Hi,

I noticed the coordinate on x-axis of the generated graph would be horizontally truncated if --shrink flag was used. It's the same in your examples.

the command to generate sashimi.pdf:
../sashimi-plot.py -b input_bams.tsv -c chr10:27040584-27048100 -g annotation.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt

But the x-axis in the graph end at around 27041500 which is way less than the 27048100 in the -c flag.

[sashimi.pdf](https://github.com/guigolab/ggsashimi/files/3613014/sashimi.pdf)

**Comment by dgarrimar** [comment]
Hi @shannjiang, this is an open issue already: #13, we are working to try to fix this asap. I close this issue as it is replicated.
