### ISSUE TITLE
Error if BAM filename starts with number

### ISSUE THREAD

**Issue by alexzaccaron** [guigolab/ggsashimi#26]
Hi,
I installed `ggsashimi` and both examples in `example_run.sh` worked fine. But when I tried with my BAM file, named `2dpi.bam`, I got the following error:
```
./sashimi-plot.py -b 2dpi.bam -c tig00000003:33700-34300

Error: unexpected symbol in "        color_list = list(2dpi"
Execution halted
```
I started to mess around with different file names and when I changed `2dpi.bam` to `dpi2.bam` it worked. It looks like if the BAM file name starts with a number `ggsashimi` gives the error above. Maybe this is an issue you would like to address in future versions of `ggsashimi`.

Package versions:
`Python v3.7.3`
`R v3.5.1`
`ggplot2 v3.2.1`
`data.table v1.12.2`
`gridExtra v2.3`

**Comment by abreschi** [comment]
Good point! Something we should definitely address soon.

**Comment by jordur** [comment]
On parse_coordinates function, I did the following modification and it worked for me:
```
def parse_coordinates(c):
        c = c.replace(",", "")
        #chr = c.split(":")[0]
        chr = c.split('\t')[0]  // HERE
        print chr
        start, end = c.split(":")[1].split("-")
        # Convert to 0-based
        start, end = int(start) - 1, int(end)
```
