### ISSUE TITLE
Plot dimension too big 

### ISSUE THREAD

**Issue by PedroBarbosa** [guigolab/ggsashimi#27]
Hi,

I'm trying to plot 26 bams separately in one single plot, but i constantly get the following error. I tried to tweak the parameters, specially the ```--height``` but it doesn't seem to work.  I can't edit the R script either to set limitsize to FALSE.  When I overlay the plot by groups I can nicely see the plot, but then when showing the reads from each sample within the same layer gets a bit messy, and I do not want to aggregate the counts in this case.

```Error: Dimensions exceed 50 inches (height and width are specified in 'in' not pixels). If you're sure you want a plot that big, use `limitsize = FALSE`.```

Any help one track per sample ? 
Best,
Pedro

**Comment by dgarrimar** [comment]
Hi @PedroBarbosa 

could you please provide some sample data to try to reproduce the error?

**Comment by PedroBarbosa** [comment]
Hi @dgarrimar ,

I don't think I have it now.  But I do believe it had to do with the number of individual samples I was plotting (in that project I had more than 30 samples). I partially solved the error by overlaying the tracks per group.

**Comment by dgarrimar** [comment]
Hi @PedroBarbosa,

I read again the error message and realized that it is just a matter of setting to true the `limitsize` flag in `ggsave`. It is fixed now.
