### ISSUE TITLE
Feature request: Add option for fixed y-axis scales

### ISSUE THREAD

**Issue by DidrikOlofsson** [guigolab/ggsashimi#28]
Hi!
In some cases it would be nice if the y-axis scale was fixed for each compared condition. I think this could help visualize differences in the inclusion levels of alternative events. There are different ways in which this feature could be implemented, one could either fix the y-scale to that of the max read count among all the plots or it could be fixed to a value that is manually entered by the user. Both of these approaches should be fairly easy to implement using standard ggplot syntax and I could try it out if this sounds interesting to anyone else!

**Comment by emi80** [comment]
Hi @DidrikOlofsson, 
thanks for pointing this out.

The feature looks quite useful and any contribution will be very welcome! We can discuss implementation details if you decide to contribute.

**Comment by DidrikOlofsson** [comment]
Hi @emi80, I'll give it a try and submit a pull request once I get that far.

**Comment by dgarrimar** [comment]
I implemented an alternative solution to allow fixed y-scales, which is now available
