### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 790: ordinal not in range(128)

### ISSUE THREAD

**Issue by mainpyp** [guigolab/ggsashimi#29]
Hi,
When im running : 

`docker run -w $PWD -v $PWD:$PWD guigolab/ggsashimi -b bam_input.tsv -c 1:138062859-138102859
`
following error occurs:<br>
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 790: ordinal not in range(128) 
`
<br>
When im running the container with one specified bam file the image works fine!
<br>
I'm using Mac OS Catalina in case if this is important.

**Comment by dgarrimar** [comment]
Hi @mainpyp,

could you please provide some sample data to try to reproduce the error?

**Comment by dgarrimar** [comment]
Hi @mainpyp, did you manage to solve the issue?

**Comment by mainpyp** [comment]
Hi @dgarrimar, no unfortunately not! I just did it twice and photoshopped them together.

**Comment by dgarrimar** [comment]
I see, did you have the problem also with the example data?

**Comment by emi80** [comment]
Hi @mainpyp, the error you see might be due to some non-ascii character in your input tsv file. Do you get the same error with the example data provided? Can you post a non working example of `bam_input.tsv`.

I will try to reproduce the issue on our side so that we can try to solve it.

**Comment by emi80** [comment]
I just found [this](https://stackoverflow.com/questions/10561923/unicodedecodeerror-ascii-codec-cant-decode-byte-0xef-in-position-1?answertab=votes#tab-top). Could you please try and let us know?

**Comment by emi80** [comment]
I can reproduce the problem. A fix will come soon.
