### ISSUE TITLE
File "sashimi-plot.py", line 214, in intersect_introns  a, b = next(it) StopIteration

### ISSUE THREAD

**Issue by TOTTW** [guigolab/ggsashimi#31]
Hi,

When I run the sashimi-plot.py it comes out this error. Could you help me solve this problem? Thank you!

> (python3) [myang9@sbcsmdplp001 ReadsCoverage]$ sashimi-plot.py -s SENSE --shrink -F png -C 2 -g Homo_sapiens.GRCh38.94.gtf -b BamR6103640ACSE98545.bam -c  chr1:196788215-196790227 -o R6103640-AC.SE_98545 
> Traceback (most recent call last):
>   File "sashimi-plot.py", line 214, in intersect_introns
>     a, b = next(it)
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "sashimi-plot.py", line 644, in <module>
>     intersected_introns = list(intersect_introns(introns))
> RuntimeError: generator raised StopIteration

**Comment by dgarrimar** [comment]
Hi @TOTTW,

could you please provide some sample data to try to reproduce the error?

**Comment by TOTTW** [comment]
Hi,
Thank you for your quick reply!
I draw the sashimi plot for a lot of bam flies. Most of them work very well. But for some Bam files, it comes the error. The case I showed before, I just found this bam file just have one reads. But when I check the other BAM file which have more than one read. It still has this error.
Below is another example:

> (base) [myang9@sbcsmdplp001 ~]$sashimi-plot.py -s SENSE --shrink -F png -C 2 -g human/ENSEMBL/Homo_sapiens.GRCh38.94.gtf -b Bam1214CERSE233625.bam -c  chr3:7686356-7691328 -o 1214_CER.SE_233625 
Traceback (most recent call last):
  File "sashimi-plot.py", line 214, in intersect_introns
    a, b = next(it)
StopIteration

> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "sashimi-plot.py", line 644, in <module>
>     intersected_introns = list(intersect_introns(introns))
> RuntimeError: generator raised StopIteration
> 
The GitHub not support to upload the bam file. So I put it to my google drive. Thank you very much!
https://drive.google.com/drive/folders/1xTeSMmS40vVCsIE6ck-LrT53GzboqX8Y?usp=sharing

**Comment by dgarrimar** [comment]
Hi, 

I have run the command you provided in one of your bam files:

`sashimi-plot.py -s SENSE --shrink -F png -C 2 -g Homo_sapiens.GRCh38.94.gtf -b Bam1214CERSE233625.bam -c chr3:7686356-7691328 -o 1214_CER.SE_233625`

with Python 3.5.6. However I could not reproduce the error. The only difference could be `Homo_sapiens.GRCh38.94.gtf`. I got it directly from ` ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz`

Does this exact command fail for you?

**Comment by TOTTW** [comment]
Thank you for your help!

**Comment by ajw2329** [comment]
Hi all - I wanted to comment briefly here that I recently encountered this error while using python v3.7.3, only when plotting exclusively samples that do not actually contain any junction reads.  Switching to python 3.6.3 solved the problem.  It seems like this might specifically relate to PEP 479 involving changes to generator behavior.  I'll dig in some more and update soon.

**Comment by yangchuhua** [comment]
When you have such an error, you can try a lower coverage cut-off. This error was reported due to the coverage cut-off being too high and rare reads left to be plotted.
