### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by archana433** [guigolab/ggsashimi#32]
./sashimi-plot.py -b input_bams.tsv -g Mus_musculus.GRCm38.99.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt
Traceback (most recent call last):
  File "./sashimi-plot.py", line 573, in <module>
    for id, bam, overlay_level, color_level, label_text in read_bam_input(args.bam, args.overlay, args.color_factor, args.labels):
  File "./sashimi-plot.py", line 176, in read_bam_input
    bam = get_bam_path(f, line_sp[1])
IndexError: list index out of range

**Comment by dgarrimar** [comment]
Hi @archana433, 

do you get any error when runnig the examples that we provide? Could you provide more details/some test dataset to try to reproduce your error? 

thanks!

**Comment by archana433** [comment]
i got error , it's the input_bam.tsv file. when i rewrite the tsv it worked.
