### ISSUE TITLE
Error in seq.default(start, max(start + 1, end - 4), by = 2425) 

### ISSUE THREAD

**Issue by archana433** [guigolab/ggsashimi#33]
$ ./sashimi-plot.py -b input_bam.tsv -g nochr_gencode_exon_transcript.gtf -c 2:29,619,720-29,740,978 -M 10 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt

Error in seq.default(start, max(start + 1, end - 4), by = 2425) : 
  'from' must be of length 1
Calls: rbind -> [ -> [.data.table -> seq -> seq.default
Execution halted

**Comment by dgarrimar** [comment]
I think you should try removing the commas for the region: `2:29619720-29740978`

**Comment by archana433** [comment]
$ ./sashimi-plot.py -b input_bam.tsv -g nochr_gencode_exon_transcript.gtf -c 2:29619720-29740978 -M 10 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt

Error in seq.default(start, max(start + 1, end - 4), by = 2425) : 
  'from' must be of length 1
Calls: rbind -> [ -> [.data.table -> seq -> seq.default
Execution halted

**Comment by dgarrimar** [comment]
Could you try only `./sashimi-plot.py -b input_bam.tsv -g nochr_gencode_exon_transcript.gtf -c 2:29619720-29740978`, also with and w/o the annotation file to get some hint on the source of the problem. In any case, could you provide some sample data to try to reproduce the error? Thanks!

**Comment by archana433** [comment]
./sashimi-plot.py -b input_bam.tsv -g nochr_gencode_exon_transcript.gtf -c 2:29619720-29740978
Error in seq.default(start, max(start + 1, end - 4), by = 2425) : 
  'from' must be of length 1
Calls: rbind -> [ -> [.data.table -> seq -> seq.default
Execution halted
 
and when i am trying without gtf it is working.

**Comment by dgarrimar** [comment]
So the problem could be the annotation. I see you use `nochr_gencode_exon_transcript.gtf`. Could you try using the full annotation? Still, it would be really useful that you provide some example data in which we can reproduce the error. It can be just a (downsampled) bam file.

**Comment by dgarrimar** [comment]
Hi @archana433, did you manage to solve the problem?

**Comment by archana433** [comment]
yes, it is solved , Thank you

**Comment by archana433** [comment]
I am getting this error again and also attaching the example data. 
./sashimi-plot.py -b example1.bam  -c 2:29619720-29740978 -g encode_mm10.transcript.exon.gtf 
Error in seq.default(start, max(start + 1, end - 4), by = 2425) : 
  'from' must be of length 1
Calls: rbind -> [ -> [.data.table -> seq -> seq.default
Execution halted


encode_mm10.transcript.exon.zip](https://github.com/guigolab/ggsashimi/files/4808999/encode_mm10.transcript.exon.zip)
[example1.zip](https://github.com/guigolab/ggsashimi/files/4809001/example1.zip)

**Comment by dgarrimar** [comment]
It seems that when there is only one intron of length shorter or equal to 5bp annotated in one of the strands (in your case the only intron annotated for transcript `ENSMUST00000051212.3`), an error arises in the arrow drawing due to an empty object. It should be fixed now.
