### ISSUE TITLE
Exons not displayed properly

### ISSUE THREAD

**Issue by cavei** [guigolab/ggsashimi#34]
Hi,
in some cases R raise a warning (Removed 1 rows containing missing values (geom_segment)) and some exons are not displayed.
I attached an example.

I run the following command

sashimi-plot -b totBs_sashimi.annot.tsv -c '1:109113929-109206781' -g TCONS_00009768_andNear.gtf -M 10 -C 3 -O 3 \
  --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt

Thanks 

[example.zip](https://github.com/guigolab/ggsashimi/files/4679004/example.zip)

**Comment by zcutts** [comment]
Really great tool! This is working really well except I am also running into this same issue where R raises a warning and removes rows, do you have any advice on how I could fix this?

Also somewhat related it seems exon tracks aren't displaying properly as seen below

<img width="1197" alt="Screen Shot 2020-07-08 at 3 35 05 PM" src="https://user-images.githubusercontent.com/54952971/86977217-046c8300-c131-11ea-9509-e1ae7f4908b1.png">

Thanks!

**Comment by dgarrimar** [comment]
Hi @cavei, the problem was related with ggplot removing the whole exon when part of it was outside the plotting limits. Now it should be fixed!
