### ISSUE TITLE
Sashimi plot read counts (above curves)

### ISSUE THREAD

**Issue by hongsilv** [guigolab/ggsashimi#35]
Hi, I'm curious about the meaning of numbers plotted above the curves (splice junction reads).

for single samples, the number seems to match the count of splice junction reads. (something like 206, 159.. )
![image](https://user-images.githubusercontent.com/52628609/84110595-1d194880-aa60-11ea-93c7-00a69d1065fa.png)

But if I input multiple samples (4 samples) in one group and draw sashimi plot, the numbers get extremely huge. (something like : 347,142,108,206). It is definitely not the sum of junction read counts in 4 samples. I wonder what those huge numbers mean.

![image](https://user-images.githubusercontent.com/52628609/84110494-f9560280-aa5f-11ea-97f9-7c68ee587ba6.png)

Thanks!

**Comment by emi80** [comment]
Hi @hongsilv,

what you see is not a big number but rather a comma separated list of counts corresponding to each input sample. I understand it might be confusing as each number has three digits and the comma looks as the thousands separator. You can also aggregate these numbers and the density plot (e.g. as the mean value) using the `-A` command line option.

Hope it helps
