### ISSUE TITLE
No y scale

### ISSUE THREAD

**Issue by silviaMDLab** [guigolab/ggsashimi#37]
I'm trying to make sashimi plot using the examples files in the example folder and just copy/paste the command line you suggested and I get the plots like the example but no y axis at all. Any clues to fix this issue?
[sashimi.pdf](https://github.com/guigolab/ggsashimi/files/4825359/sashimi.pdf)

**Comment by antonioggsousa** [comment]
Hi, 

I had the same problem and I downgrade the version of `ggplot2` from >3 to 2.2.1 and now just works fine. 

So, I might consider to downgrade the version of ggplot2: 

`devtools::install_version("ggplot2", version = "2.2.1", repos = "http://cran.us.r-project.org")`

This is not the best solution, but with a two lines you can downgrade and update again after running the program `ggplot2`. 

I hope this helps, 

António

**Comment by dgarrimar** [comment]
Hi @silviaMDLab, @antonioggsousa,

could you please provide the exact `ggplot2 ` version that leads to this problem?

**Comment by antonioggsousa** [comment]
Hi @dgarrimar, 

Mine is `ggplot2` version is: `3.3.2`

Thx!
António

**Comment by dgarrimar** [comment]
Hi @silviaMDLab, @antonioggsousa, it should be fixed now

**Comment by antonioggsousa** [comment]
Hi @dgarrimar, 

Thx! I just tested and it works fine with `ggplot2 v. 3.3.2`

Thank you, 

António
