### ISSUE TITLE
No reads in the specified Area error 

### ISSUE THREAD

**Issue by padwalmk** [guigolab/ggsashimi#38]
Hi, 
I am using the ggsashmi to plot some of the transcripts from gtf file, However when I see in the IGV there are reads for exons as well as junctions. However, when I run sashami-plot script I get error "No reads in the specified area."
Example jpeg for the transcripts from IGV. 

I am running following command for the plotting. 
sashimi-plot.py -b bam_list  -C 4 -L 3 -c chr22:39696699-39700075 -o MSTRG10006 -g ../Final_novel.gtf  
![Screenshot from 2020-06-30 10-25-20](https://user-images.githubusercontent.com/55156932/86085150-0e044400-babc-11ea-8c7f-e3c1abb63912.png)

**Comment by emi80** [comment]
Hi @padwalmk,
apologies for the late reply. 

Could you please check that the chromosome name in the bam corresponds with the one you passed via command line (I cannot see the chromosome name in the IGV screenshot)? If everything looks fine, could you please send us a small example to reproduce the issue?

**Comment by padwalmk** [comment]
Hi, 
Thank you for the reply, Actually I was using ggshashami script for plotting novel lncRNA from bam files. These lncRNAs are not expressed et al in some of the samples so, when script encounter such samples it throw error and take exit.

I have changed the code and remove the exit(1) from code and now I am getting plot. However, I now encounter new problem, I have given colour details for three group, but I am getting color plot for only one group. I am attaching a sample file produced after changing code.  This is example file, where lymph-node-metastasis should have blue and primary should have green color but I am getting only gray in two samples. 
![MSTRG20120 1](https://user-images.githubusercontent.com/55156932/87039424-c349a100-c20c-11ea-88d5-2670925eef13.jpeg)

**Comment by padwalmk** [comment]
Thank you, I have tried you updated script, and it throw another eroor ... 

"Traceback (most recent call last):
  File "/usr/local/bin/sashimi-plot.py", line 671, in <module>
    R_script += make_R_lists(id_list, bam_dict[strand], overlay_dict, args.aggr, intersected_introns)
  File "/usr/local/bin/sashimi-plot.py", line 491, in make_R_lists
    x, y, dons, accs, yd, ya, counts = d[k]
KeyError: u'SRR5553891'"

But when I removed continue from line in which you have added, it run smoothly. But the colour for group is still not coming. Another thing When I try to overlay with same code, it draw colour but the not as specified by color setting. 

Thank you for quick response.

**Comment by emi80** [comment]
I can have a look at this. But having a small example to reproduce the problem would really help to debug it.

Thanks.

**Comment by emi80** [comment]
The new HEAD on dev should fix this. Please let me know if it works.

If it is fine, I would move the color problem to another GitHub issue.

Thanks a lot.

**Comment by padwalmk** [comment]
Hi, 
Thank you sure, I will try and let you know, uploading data and mail you link for sample data. 



> The new HEAD on dev should fix this. Please let me know if it works.
> 
> If it is fine, I would move the color problem to another GitHub issue.
> 
> Thanks a lot.
