### ISSUE TITLE
Warnings when using -A mean_j (median_j)

### ISSUE THREAD

**Issue by dgarrimar** [guigolab/ggsashimi#39]
The test example raises some warnings when `-A mean_j` or `-A median_j` option is set:

`../sashimi-plot.py -b input_bams.tsv  -c chr10:27040584-27048100 -g annotation.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt -A mean_j
`

`
There were 18 warnings (use warnings() to see them)
`

And the arches in the output plot start from (and end into) wrong signal values

**Comment by emi80** [comment]
The code responsible for this (from [these lines](https://github.com/guigolab/ggsashimi/blob/master/sashimi-plot.py#L741:L744)):
```
if ("%(args.aggr)s" != "") {
    j[3] = as.numeric(d[x==j[1]-1,y])
    j[4] = as.numeric(d[x==j[2]+1,y])
}
```
This happens since `d[x==j[1]-1,y]` is a list of values. The first one is used end the warning is given.
