### ISSUE TITLE
something missing in graphic

### ISSUE THREAD

**Issue by lmanchon** [guigolab/ggsashimi#4]
--Hi,
i generate the graphic with this command:
./sashimi-plot.py -b input_bams.tsv -c 11:5617339-5625858 -g exons.gtf -M 10 -C 3 -O 3 -A median -F tiff -R 350 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt

but the arrows between exons (below the sashimi plots) are not drawn.

an idea ?
thank you --

**Comment by jlboat** [comment]
I recommend checking out the issue I opened (now closed: Axes labels missing #3).

The best reason I could come up with was an environment issue. So, either use Singularity, as I did, or Docker to get around the problem.

**Comment by dgarrimar** [comment]
Hi @lmanchon, did you finally solve the problem? It seems to me that as @jlboat suggests, it may be an environment problem: using Docker/Singularity will get around it. Let me know if you still have some trouble with this!

**Comment by lmanchon** [comment]
-Hi,

nothing change for me:
git clone https://github.com/guigolab/ggsashimi.git
cd ggsashimi/examples
singularity pull docker://guigolab/ggsashimi
singularity run ggsashimi.simg -b input_bams.tsv -c 11:5617339-5625858 -g exons.gtf -M 10 -C 3 -O 3 --ann-height=4 --height=3 --width=18 -P palette.txt

see attachment.
[sashimi.pdf](https://github.com/guigolab/ggsashimi/files/2370497/sashimi.pdf)

**Comment by dgarrimar** [comment]
I see. From your pdf I think it could be a problem with the annotation file format. Could you provide a copy of your gtf file? Make sure it contains `gene`, `transcript` and `exon` features, and not only the exons; and also the attribute `transcript_id` in the comma separated list as in [our sample annotation](https://github.com/guigolab/ggsashimi/blob/master/examples/annotation.gtf).

**Comment by dgarrimar** [comment]
It seems you only have `exon` features in the third field of your `gtf`: 

```bash
zcat exons.gtf.gz | cut -f3 | sort | uniq -c
# 613754 exon
```

Please, try what I suggested in https://github.com/guigolab/ggsashimi/issues/4#issuecomment-420222960 and let me know.

**Comment by lmanchon** [comment]
--Hi,
in my gtf file (dowloaded from Ensembl website) i have only 4 features: 
cat Homo_sapiens.GRCh37.70.gtf | cut -f3 | sort | uniq -c
 794920 CDS
1309155 exon
  92839 start_codon
  83698 stop_codon

**Comment by dgarrimar** [comment]
Maybe you can try [GENCODE annotation](https://www.gencodegenes.org/releases/)

**Comment by lmanchon** [comment]
--
i have downloaded this file from gencode: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
then: zcat gencode.v19.annotation.gtf.gz | sed '1,5d;s/chr//' > gencode.v19.annotation.gtf
singularity run ggsashimi.simg -b input_bams.tsv -c 11:5617339-5625858 -g gencode_annotation.gtf -M 10 -C 3 -O 3 --ann-height=4 --height=3 --width=18 -P palette.txt
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
Warning message:
Removed 2 rows containing missing values (geom_segment).

now the arrows are drawn:

[sashimi.pdf](https://github.com/guigolab/ggsashimi/files/2370715/sashimi.pdf)

**Comment by dgarrimar** [comment]
Hi, @lmanchon, this seems to solve the problem, right?

**Comment by lmanchon** [comment]
--Hi,

yes, you can close the issue.
thank you --

**Comment by dgarrimar** [comment]
Thank you!
