### ISSUE TITLE
How to generate transcript diagram at the bottom

### ISSUE THREAD

**Issue by HeenaSaini** [guigolab/ggsashimi#43]
Hi, I want to ask how to generate the transcript diagram (that consists transcript id and strand) at the bottom of sahsimi plot as you have generated in your example. I have tried, But I am not getting anything at the bottom..
Thanks 
Heena

**Comment by dgarrimar** [comment]
Hi @HeenaSaini, 

the annotation layer is generated with option `-g`. In our example:

```
# Example #1. Overlay, intron shrinkage, gene annotation, PDF output, custom size and colors
../sashimi-plot.py -b input_bams.tsv -c chr10:27040584-27048100 -g annotation.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt
```


You mean you cannot reproduce the example or that it does not work with your data? It could be a dependencies issue (which versions of R/python/ggplot2 are you using? have you tried using our Docker image?) or a problem with the format of the annotation (please double check your `gtf` file). In any case, can you provide some extra details on the problem or a small dataset so that we can reproduce the problem?

Thanks!

**Comment by HeenaSaini** [comment]
I am not able to generate or pull docker image: it says: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock
so I am trying with ./sashimi-plot.py script-
ggsashimi/sashimi-plot.py -b path_my_bams.tsv -c chr14:64084232-64338631 -g UCSC_hg38_knownGenes_22sep2014.gtf -o sashimiEsr2

I do not know how to share the dataset with you - I am not able to past or drag and drop files here in this section.
I am not able to create the transcript lines with their names at the bottom..

I am able to correctly reproduce the diagram as you have mentioned with your example data,

But I am not able to get it with mine.
Also, I am getting this error sometimes:
Traceback (most recent call last):
  File "ggsashimi/sashimi-plot.py", line 632, in <module>
    transcripts, exons = read_gtf(args.gtf, args.coordinates)
  File "ggsashimi/sashimi-plot.py", line 288, in read_gtf
    d = dict(kv.strip().split(" ") for kv in tags.strip(";").split("; "))
ValueError: dictionary update sequence element #6 has length 6; 2 is required

but at other times, the script runs fine..

**Comment by HeenaSaini** [comment]
my gtf file looks like this: 
$ head UCSC_hg38_knownGenes_22sep2014.gtf 
chr1	hg38_knownGene	exon	11874	12227	0	+	.	gene_id "uc001aaa.3"; transcript_id "uc001aaa.3"; geneSymbol "DDX11L1"; mRNA "NR_046018"; refseq "NR_046018"; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "DDX11L1"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	exon	12613	12721	0	+	.	gene_id "uc001aaa.3"; transcript_id "uc001aaa.3"; geneSymbol "DDX11L1"; mRNA "NR_046018"; refseq "NR_046018"; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "DDX11L1"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	exon	13221	14409	0	+	.	gene_id "uc001aaa.3"; transcript_id "uc001aaa.3"; geneSymbol "DDX11L1"; mRNA "NR_046018"; refseq "NR_046018"; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "DDX11L1"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	exon	11874	12227	0	+	.	gene_id "uc001aab.3"; transcript_id "uc001aab.3"; geneSymbol "DDX11L1"; mRNA "AM992878"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992878"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	exon	12646	12697	0	+	.	gene_id "uc001aab.3"; transcript_id "uc001aab.3"; geneSymbol "DDX11L1"; mRNA "AM992878"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992878"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	exon	13221	14409	0	+	.	gene_id "uc001aab.3"; transcript_id "uc001aab.3"; geneSymbol "DDX11L1"; mRNA "AM992878"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992878"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "NA"; knownCanonicalChromStart "NA"; knownCanonicalChromEnd "NA"; knownCanonicalClusterId "NA"; tss_id "TSS1";
chr1	hg38_knownGene	start_codon	12190	12192	0	+	.	gene_id "uc010nxq.1"; transcript_id "uc010nxq.1"; geneSymbol "DDX11L1"; mRNA "AM992880"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992880"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "chr1"; knownCanonicalChromStart "11873"; knownCanonicalChromEnd "14409"; knownCanonicalClusterId "1"; tss_id "TSS1"; p_id "P1";
chr1	hg38_knownGene	CDS	12190	12227	0	+	0	gene_id "uc010nxq.1"; transcript_id "uc010nxq.1"; geneSymbol "DDX11L1"; mRNA "AM992880"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992880"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "chr1"; knownCanonicalChromStart "11873"; knownCanonicalChromEnd "14409"; knownCanonicalClusterId "1"; tss_id "TSS1"; p_id "P1";
chr1	hg38_knownGene	exon	11874	12227	0	+	.	gene_id "uc010nxq.1"; transcript_id "uc010nxq.1"; geneSymbol "DDX11L1"; mRNA "AM992880"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992880"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "chr1"; knownCanonicalChromStart "11873"; knownCanonicalChromEnd "14409"; knownCanonicalClusterId "1"; tss_id "TSS1"; p_id "P1";
chr1	hg38_knownGene	CDS	12595	12721	0	+	1	gene_id "uc010nxq.1"; transcript_id "uc010nxq.1"; geneSymbol "DDX11L1"; mRNA "AM992880"; refseq ""; protAcc ""; description "Homo sapiens DEAD/H (Asp-Glu-Ala-Asp/His) box helicase 11 like 1 (DDX11L1), non-coding RNA."; locusLink "100287102"; alias "AM992880"; knownToRefSeq "NR_046018"; knownIsoformsClusterID "1"; knownCanonicalChrom "chr1"; knownCanonicalChromStart "11873"; knownCanonicalChromEnd "14409"; knownCanonicalClusterId "1"; tss_id "TSS1"; p_id "P1";

**Comment by HeenaSaini** [comment]
Also I want to ask - how to get the name of the group in the left - my output is showing sample ID,
but like in your example - it is endothelial, mesenchymal etc. I have mentioned group id in the third col of the TSV file..

**Comment by HeenaSaini** [comment]
I got it - thanks a lot..

**Comment by dgarrimar** [comment]
Great, what was happening? Can we help you with something else?

**Comment by HeenaSaini** [comment]
I think  the problem was with GTF file, I used a different file, with protein coding primary assembly, I am able to get the transcript diagram at the bottom. Thanks a lot for your help.
