### ISSUE TITLE
Add exception for GTF files with gene rows as well

### ISSUE THREAD

**Issue by abreschi** [guigolab/ggsashimi#46]
I think now we currently support only gtf files with transcripts and exons, assuming that gene rows would still have a `transcript_id` tag in the metadata. Unfortunately, newer gtf formats do not have `transcript_id` for genes anymore and it throws error. We should add an exception for this

**Comment by dgarrimar** [comment]
Fixed in d7a9a9d824e2ad6d4befd2c66e39a5feba47e731
