### ISSUE TITLE
Change font size of transcript id when using `-gtf`

### ISSUE THREAD

**Issue by ManavalanG** [guigolab/ggsashimi#5]
I would like to change the size of transctipt id when using `--gtf`, but I am not sure which part of the R script needs to be modified to achieve this. Could you point to the part of the script that controls this? Thanks!

**Comment by dgarrimar** [comment]
Hi @ManavalanG, currently to change the size of the annotation labels you can use the option `--base-size`, but this will also change the size of the rest of the text in the plot. As a quick workaround, you can substitute line 420 of `sashimi-plot.py`:

```R
gtfp = gtfp + theme(axis.line = element_blank(), axis.text.x = element_blank(), axis.ticks = element_blank())
```
by (for instance):

```R
gtfp = gtfp + theme(axis.line = element_blank(), axis.text.x = element_blank(), axis.ticks = element_blank(), text = element_text(size=20))
```
This will set size=20 only to the annotation labels. Please let me know if you managed to solve it!

**Comment by dgarrimar** [comment]
Hi @ManavalanG, did this work for you?

**Comment by emi80** [comment]
Maybe we should update the help message before closing this

**Comment by dgarrimar** [comment]
Ups indeed,

Thanks,

Diego
