### ISSUE TITLE
Annotation and density plots are not aligned with ggplot2 version greater than 2.2.1

### ISSUE THREAD

**Issue by emi80** [guigolab/ggsashimi#6]
In ggplot2 versions greater that 2.2.1 grobs have a different number of colums

**Comment by emi80** [comment]
As discussed with @dgarrimar we coudl use:
```
grob$widths[grob$layout$r[grob$layout$name=="axis-l"]]
```
to select widths

**Comment by dgarrimar** [comment]
As discussed with @emi80 and @abreschi, a temporary solution would be to attach to `ggplot2` v2.2.1 or use our docker image. We are working to fix this issue as soon as possible.

**Comment by dgarrimar** [comment]
Hi @shinyanishio, did you build the Docker image yourself from the Dockerfile or got it from DockerHub?

**Comment by dgarrimar** [comment]
As it claims in the README, `docker pull guigolab/ggsashimi` allows you to get the Docker image from DockerHub. It seems that after pulling it you have built a new one on top by running `docker build` (this steps are __alternative__). While the former should contain the right version of `ggplot2`, the latter does not, as the libraries got updated. Just remove the image that you built and run  `docker pull guigolab/ggsashimi` again to get the original container. Then it should work properly!

**Comment by dgarrimar** [comment]
I updated the README file to clarify this

**Comment by shinyanishio** [comment]
Thank you for your help!! Now we can draw apropriately !!
