### ISSUE TITLE
collapsed colouring options 

### ISSUE THREAD

**Issue by AMChalkie** [guigolab/ggsashimi#63]
Hi,

Is there a way to set the colours for each replicate to be different when replicates are collapsed? I can't quite get the behaviour I would like - which is greater contrast between the collapsed replicate colours.

Also within this, I tried different transparency options using --alpha but they seem to make no difference. 

Guidance appreciated.

Best wishes
Alistair

**Comment by dgarrimar** [comment]
Hi @AMChalkie, unfortunately, the current implementation does not allow different colors for different samples aggregated via `--overlay`. How many samples are you plotting? Maybe it is a matter of choosing the good combination of colour+transparency. Can you show an example plot to try to understand why `--alpha` is not working well in your case?

**Comment by AMChalkie** [comment]
Hi,
It is understandable as this is a bit of an outlier case for colouring. The setup is 3 reps * 2 conditions, so that part is pretty standard. We've gone the manual route to fix for publication. Can't show you the particular graphs right at the moment, but it was very odd, alphas of 0.1 and 0.9 produced the same plot.

**Comment by dgarrimar** [comment]
I see, well still it would be great to have an example to try to understand why this happens, even if it is a different region.
