### ISSUE TITLE
junction shift

### ISSUE THREAD

**Issue by Vita-github** [guigolab/ggsashimi#65]
I am trying to plot the same sample with different --min-coverage parameter. When I change -M from 250 to 600, the junction shifts from exonic to intronic. How is that possible? In both instances I am using --shrink parameter. Is there an option which fixes this problem?

Thank you for your time, Vita
![intron-exon](https://user-images.githubusercontent.com/61147571/113140178-58237d00-9228-11eb-9db5-b9869c961725.jpg)

**Comment by dgarrimar** [comment]
Hi @Vita-github, that looks strange indeed! Could you please provide some test dataset to see what's going on?
