### ISSUE TITLE
ggsashimi doesn't work on my data

### ISSUE THREAD

**Issue by Aikaterini-Chatzipli** [guigolab/ggsashimi#66]
Hello ggsashimi developers, 

I encountered a problem when using ggsashimi on my data. I tried the example provided in your package and that worked fine but when I run ggsashimi on my bam files I got the following error:

../ggsashimi.py -b input.b.vs.l.bams.tsv -c 14:51221585-51226575 -g annotation.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt -F png

Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
Calls: ggplotGrob ... expand_limits_discrete_trans -> expand_limits_continuous_trans -> ifelse
In addition: Warning message:
In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL
Execution halted

Have you seen this error before and if so, is it possible to interpret it?

Many thanks, 

Katerina

**Comment by dgarrimar** [comment]
Hi, @Aikaterini-Chatzipli, please use the appropriate template for a bug report. Could you also provide some example data to try to reproduce the error? Thank you!

**Comment by Aikaterini-Chatzipli** [comment]
Hello, apologies for the confusion. The issue I was having was related to the annotation I used and it has been resolved. Please close this ticket.

Many thanks

**Comment by juliandwillett** [comment]
For anyone who saw where this ticket led, I found that you needed the right assembly annotation file. So if you are using GRCh37, you want an appropriate GTF file from Pubmed. You will also want an annotation file covering your desired regions
