### ISSUE TITLE
variant annotation

### ISSUE THREAD

**Issue by hkmztrk** [guigolab/ggsashimi#67]
Hello, I was wondering whether it is possible to annotate a point(s) on the plot? Another question is that whether I can print out the plot in textual form or not? Thanks!

**Comment by dgarrimar** [comment]
Hi @hkmztrk, in it's current version, in principle it is not possible to add custom annotations in the plot. What would you like to add? A vertical bar or a point to indicate the position of a SNP? I guess this could be done after small modifications of the code if needed. Regarding your second question, what do you mean by 'textual' form? If you mean 'vectorized', yes you have PDF output format for instance.

**Comment by hkmztrk** [comment]
Hi @dgarrimar, thanks a lot for your reply! Yes, exactly, a vertical through the position of a SNP would be great. [I could also try to do this locally if you could point me out the part I need to modify]

Yes, let me clarify that, for instance in the image below, is it possible get these junction numbers for the coordinates in text form, e.g

pos1-pos2 12
pos3-pos4 141
pos5-pos6 85
pos7-pos8 68
pos5-pos8 23

<img width="393" alt="Screenshot 2021-05-06 at 16 48 52" src="https://user-images.githubusercontent.com/4271817/117318769-060af280-ae8b-11eb-8bb4-f92606fe1449.png">

**Comment by dgarrimar** [comment]
I see, yes, you can get a BED file with the junction positions and counts with the option `-j`. Regarding the other point I now realize it may not be that straightforward when using `--shrink`, as the SNP coordinate needs to be shrinked too. If not using `--shrink`, you may be able to do it by simply adding a `geom_vline(xintercept = POSITION_OF_THE_SNP)` to the ggplot

**Comment by hkmztrk** [comment]
Seems like I missed `-j` argument! Ah okay, so far I was using `--shrink` but I'll try it the other way to add annotation. 

Thanks a lot for your help!
