### ISSUE TITLE
Exon annotation not matching read coverage visualization

### ISSUE THREAD

**Issue by paulklemm** [guigolab/ggsashimi#70]
## Bug report

I've experienced a bug where the transcript exons are off, but the plot itself looks correct.

### Expected behavior and actual behavior

The sashimi plots using the IGV looks as follows:

![Sashimi](https://user-images.githubusercontent.com/2169489/129202559-697ed630-8371-41a3-9025-ed51d44f2ce2.png)

The ggsashimi plot looks as follows:

![Pasted_Image_12_08_21__15_17](https://user-images.githubusercontent.com/2169489/129203901-289dedfb-6664-4ac1-8105-fe88046ae0ee.png)

The transcript of interest is the one at the bottom.

In IGV, the exons perfectly overlap. In ggsashimi, there seems to be a constant shift. I guess I do something wrong with preparing the GTF file. Here is my full script.

```bash
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz
zcat gencode.vM27.annotation.gtf.gz | sed '1,5d;s/chr//' > gencode.vM27.annotation.gtf
rm gencode.vM27.annotation.gtf.gz
gzip gencode.vM27.annotation.gtf

singularity run ${SINGULARITY_IMAGES}/ggsashimi_latest.sif \
  -b input_bams_debug.tsv \
  -c 8:3148922-3281649 \
  -A mean \
  -g gencode.vM27.annotation.gtf.gz \
  -C 3 \
  -O 3 \
  -M 10 \
  --base-size=20 \
  --ann-height=4 \
  --height=3 \
  --width=18 \
  -P palette.txt \
  --fix-y-scale
```

I'm on the latest docker container, running it on a HPC environment using singularity.

Any pointers on where I went wrong?

**Comment by emi80** [comment]
Hi @paulklemm,
I don't see anywhere you went wrong. You could possibly try running ggsashimi in debug mode and check R script that is used to produce the plot. You can find how to do so in the README.

On the other hand, would it be possible for you to share a small subset of the bam files you are using, in order to reproduce the problem on our side and be able to debug it?
