### ISSUE TITLE
Coordinates of splicing events

### ISSUE THREAD

**Issue by nick294** [guigolab/ggsashimi#72]
Hi,

Is there an option to obtain the coordinates for the splicing events that ggsashimi is calling? I've managed to make the visualization, but cannot figure out the location of these events and was wondering if there is an easy way to extract this information, as well as the read coverage attributed to each splicing event shown in the visualization. 

Thanks,
Nick

**Comment by emi80** [comment]
Hi @nick294,
thanks for your question. You can use [this](https://github.com/guigolab/ggsashimi/blob/master/ggsashimi.py#L61:L62) command line option to write the junctions' list to a BED file. 
By the way, you can see all available options running ggsashimi with the `--help` option as stated in the usage section of the [README](https://github.com/guigolab/ggsashimi/blob/master/README.md)

Best,
Emilio
