### ISSUE TITLE
Error in R

### ISSUE THREAD

**Issue by hmyh1202** [guigolab/ggsashimi#79]
$../ggsashimi.py -b input_bams.tsv -c chr10:27040584-27048100 -g annotation.gtf -M 10 -C 3 -O 3 --shrink --alpha 0.25 --base-size=20 --ann-height=4 --height=3 --width=18 -P palette.txt
[W::hts_idx_load3] The index file is older than the data file: bams/ENCFF450AIU.chr10_27035000_27050000.bam.bai
[W::hts_idx_load3] The index file is older than the data file: bams/ENCFF960FZU.chr10_27035000_27050000.bam.bai
Warning messages:
1: In density_grobs[[id]]$widths[1] <- density_grobs[[id]]$widths[1] +  :
  number of items to replace is not a multiple of replacement length
2: In density_grobs[[id]]$widths[3 + vs] <- maxYtextWidth :
  number of items to replace is not a multiple of replacement length
3: In density_grobs[[id]]$widths[1] <- density_grobs[[id]]$widths[1] +  :
  number of items to replace is not a multiple of replacement length
4: In density_grobs[[id]]$widths[3 + vs] <- maxYtextWidth :
  number of items to replace is not a multiple of replacement length
5: In density_grobs[[id]]$widths[1] <- density_grobs[[id]]$widths[1] +  :
  number of items to replace is not a multiple of replacement length
6: In density_grobs[[id]]$widths[3 + vs] <- maxYtextWidth :
  number of items to replace is not a multiple of replacement length
7: In density_grobs[[id]]$widths[1] <- density_grobs[[id]]$widths[1] +  :
  number of items to replace is not a multiple of replacement length
8: In density_grobs[[id]]$widths[3 + vs] <- maxYtextWidth :
  number of items to replace is not a multiple of replacement length
9: In density_grobs[[id]]$widths[1] <- density_grobs[[id]]$widths[1] +  :
  number of items to replace is not a multiple of replacement length
10: In density_grobs[[id]]$widths[3 + vs] <- maxYtextWidth :
  number of items to replace is not a multiple of replacement length
Error in grid.Call.graphics(L_setviewport, vp, TRUE) :
  INTEGER() can only be applied to a 'integer', not a 'NULL'
Calls: ggsave ... lapply -> FUN -> push.vp.viewport -> grid.Call.graphics
Execution halted

I  have  got a error in using ggsashimi.py with the example data.

So what is mean of the error ? thank U.

**Comment by dgarrimar** [comment]
Hi @hmyh1202 Uhm.. it seems it could be related to the version of R/ggplot that you are using. Could you please let us know which versions are you using to try to reproduce the problem? You should not have problems using the Docker image.
