### ISSUE TITLE
error regarding intersect_introns

### ISSUE THREAD

**Issue by xiaonalu** [guigolab/ggsashimi#81]
Hi, I am afraid I have reads located in the introns, because I receive below error. Could I still generate a plot with these introns included? Any flag to use? Thanks
Best
Xiaona

Traceback (most recent call last):
  File "./ggsashimi.py", line 253, in intersect_introns
    a, b = next(it)
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./ggsashimi.py", line 746, in <module>
    intersected_introns = list(intersect_introns(introns))
RuntimeError: generator raised StopIteration

**Comment by dgarrimar** [comment]
Hi Xianoa, could you please provide a small sample dataset to try to reproduce the problem?

**Comment by xiaonalu** [comment]
Hi, Please find attached files. Thanks for your help
Best
Xiaona
________________________________

**Comment by xiaonalu** [comment]
sorry, could the attachments reach you through the email? or I'd better transfer them by a different way? Thanks
Best
Xiaona
________________________________

**Comment by dgarrimar** [comment]
I did not get anything, try attaching them here directly if they are small enough, otherwise please share a link pointing to them

**Comment by xiaonalu** [comment]
Could below link work? Thanks
https://drive.google.com/drive/folders/1KizNYIJzjOKcBLAn-QknnUMoKYhqYVYj?usp=sharing
________________________________

**Comment by xiaonalu** [comment]
Hello, I added your email address to the google folder. Does it work? Thanks

**Comment by xiaonalu** [comment]
I am thinking if this is due to I am using long reading rna sequencing data, while Sashimi is only for short reads? Thanks

**Comment by dgarrimar** [comment]
I got the files, give us some time to review them. In principle ggssashimi was designed for short reads, and although it may work for long reads, it has not been tested yet, so this could be the reason why it fails.

**Comment by xiaonalu** [comment]
Thank you so much
________________________________

**Comment by sum732** [comment]
Hello,
I am seeing exactly the same error:
```
Traceback (most recent call last):
  File "Programs/ggSashimi/ggsashimi.py", line 253, in intersect_introns
    a, b = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./Programs/ggSashimi/ggsashimi.py", line 746, in <module>
    intersected_introns = list(intersect_introns(introns))
RuntimeError: generator raised StopIteration
```
My data is all from short read. 
Regarding one of the comments above, Intron retention can happen and RNA-Seq will detected that. Why could that be an issue? 

Best,
Deep

**Comment by dgarrimar** [comment]
Sorry I cannot access anymore the test bam files that you provided @xiaonalu, could you please share them again? Thank you!

**Comment by lilyku26** [comment]
Hi there,
I have also seen the same error, wondering how to fix it.

> Traceback (most recent call last):
  File "/Users/litingku/Downloads/ggsashimi.py", line 253, in intersect_introns
    a, b = next(it)
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/litingku/Downloads/ggsashimi.py", line 746, in <module>
    intersected_introns = list(intersect_introns(introns))
RuntimeError: generator raised StopIteration

the Python version I used is Python 3.8.8
The code I run:

` python /Users/litingku/Downloads/ggsashimi.py \`
`--bam /Users/litingku/Downloads/SRR12900848/Aligned.sortedByCoord.out.bam \`
`--coordinates chr2:120735623-120992653 \`
`--out-prefix /Users/litingku/Downloads/SUPPA2/GLI2_chr2:120735623-120992653 \`
`--gtf /Users/litingku/Downloads/Homo_sapiens.GRCh38.94.gtf \`
`--out-format png \`
`--out-resolution 600 \`
`--overlay 3 \`
`--aggr median \`
`--color-factor 3 \`
`--palette /Users/litingku/Downloads/color.txt \`
`--fix-y-scale \`
`--min-coverage 100 \`
`--shrink`

The files I use are here:[https://drive.google.com/drive/folders/1gv6tDY_WmyY_N4vaFNjr8s5K6E1PhUFR?usp=sharing](url)

Thank you so much :D 

Best.
Li-Ting

**Comment by MB571** [comment]
Hi I'm getting the same issue
