### ISSUE TITLE
C stack usage error

### ISSUE THREAD

**Issue by umranyaman** [guigolab/ggsashimi#83]
Hello,

I am having the error below when I run
python ggsashimi.py -b input_bams.tsv -c chr7:19430034-19433113 -g gencode.vM28.chr_patch_hapl_scaff.annotation.gtf -o ggsashimi -F png

Error: C stack usage  7969676 is too close to the limit
Execution halted

I have 12 bam files from long-read RNA-seq data and running this on the server. 

How can I solve this, perhaps should I use bam files from chr7 only? 

Thanks very much
Umran

**Comment by dgarrimar** [comment]
Hi @umranyaman Did you manage to solve it in the end?
