### ISSUE TITLE
Error in FUN(X[[i]], ...) : object 'V1' not found

### ISSUE THREAD

**Issue by sopenaml** [guigolab/ggsashimi#84]
## Bug report
Running your docker container on singularity, as docker is not supported on our cluster:

 ```
singularity run -B /camp ggsashimi.sif  -b scripts/input_bam.tsv -c 4:106662256-106662259 -g $gtf -C 3 -O 3 -P scripts/palette.txt
Error in FUN(X[[i]], ...) : object 'V1' not found
Calls: ggplotGrob ... ggplot_build.ggplot -> by_layer -> f -> <Anonymous> -> f -> lapply -> FUN
Execution halted
```

The same command works for other chr coordinates.  

Debugging:

 ```
singularity run -B /camp ggsashimi.sif  -b scripts/input_bam.tsv -c 4:106662256-106662259 -g $gtf -C 3 -O 3 -P scripts/palette.txt --debug-info
ERROR: [Errno 2] No such file or directory: 'lsb_release'
```

**Comment by emi80** [comment]
Hi @sopenaml,

the region you are looking for is just 3 bases, so it's really small and might lead to the issue. Also, did you check that there are mapped reads in your BAM files for that region?

About the error in the debugging command, you are not supposed to run that command when using `ggsashimi` in a container. Actually, it was not clear so we updated the issue template. Thanks.
