### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by naqvia** [guigolab/ggsashimi#91]
I am trying to set the colors but it always seems to be grey (both groups). I have pasted the color palette, my bam file tsv, and command. 

```
ctrl	bams/6c37714d-e692-4982-a817-67818765a241.Aligned.out.sorted.bam	ctrl
tumor	bams/48645a9d-5f53-4db7-8b66-f0b0e5bbeb52.Aligned.out.sorted.bam	tumor
```

```
orange
cornflowerblue
```
```
docker run --platform linux/amd64 -w $PWD -v $PWD:$PWD guigolab/ggsashimi -b input_bams.tsv -c chr2:200853009-200864658 -g gencode.v33.annotation.transcr.gtf --shrink --alpha 0.15 --base-size=20 --ann-height=1.5 --height=3 --width=18 -P palette.txt
```

Am I doing something wrong?

**Comment by bdgsilva** [comment]
@naqvia, you need to use the parameter --color-factor with the number (1-based) of the column in your bam config file that specifies what you want to color (in your case, columns 1 or 3)
