### ISSUE TITLE
Executing ggsashimi with singularity

### ISSUE THREAD

**Issue by amberdeja** [guigolab/ggsashimi#93]
Hello, 

I downloaded the script and the entire repository but I am having trouble executing ggsashimi with docker using singularity, which is what is installed at the UCSF cluster.

[amartinez@c4-n1:job=1468300 ggsashimi]$ singularity run guigolab/ggsashimi --help
FATAL:   could not open image /c4/home/amartinez/sashimi/ggsashimi/guigolab/ggsashimi: failed to retrieve path for /c4/home/amartinez/sashimi/ggsashimi/guigolab/ggsashimi: lstat /c4/home/amartinez/sashimi/ggsashimi/guigolab: no such file or directory

Could you please help me get ggsashimi to work with singularity? Should I use a different path than the one provided in GitHub?

Thank you and best wishes,
Alejandra

**Comment by emi80** [comment]
Hi @amberdeja,

in order to run Docker images with Singularity you need to prepend `docker://` to the image, e.g. for `ggsashimi`:

```
singularity run docker://guigolab/ggsashimi
```

This is related to Singularity usage in general and it is not `ggsashimi` specific.

Best,
Emilio

**Comment by amberdeja** [comment]
Hello Emilio,

Thank you for your help. This line runs fine now:
singularity run docker://guigolab/ggsashimi --help

However, I followed the directions on GitHub and then tried to replicate the command line in the examples and I have not been able to run the script. I posted the warning messages with the lines I tried to run below the email.

I also have a few other questions.
1)	Is it okay to use a sorted .gtf? 
2)	I attached my .tsv file with the files I am trying to run. Is my .tsv correct?

Can I get some help on running ggsashimi? This is my email in case it is easier to do this by email: amberdeja@ucdavis.edu

Thank you and best wishes, 
Alejandra

[amartinez@c4-n4:job=1475857 sashimi]$ singularity run -w $PWD -v $PWD:$PWD docker://guigolab/ggsashimi -b sashimi_try2.tsv -c chr12:25358180-25403870 -g $f
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: By using --writable, Apptainer can't create /dev destination automatically without overlay or underlay
FATAL:   container creation failed: mount hook function failure: mount /dev->/dev error: while mounting /dev: destination /dev doesn't exist in container


<amartinez/sashimi -v /c4/home/amartinez/sashimi:/c4/home/amartinez/sashimi docker://guigolab/ggsashimi -b sashimi_try2.tsv -c chr12:25358180-25403870 -g $f                                           
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: By using --writable, Apptainer can't create /dev destination automatically without overlay or underlay
FATAL:   container creation failed: mount hook function failure: mount /dev->/dev error: while mounting /dev: destination /dev doesn't exist in container

[amartinez@c4-n4:job=1475857 sashimi]$ singularity run -w /c4 -v /c4:/c4 docker://guigolab/ggsashimi /c4/home/amartinez/sashimi/ggsashimi.py -b sashimi_try2.tsv -c chr12:25358180-25403870 -g $f
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: By using --writable, Apptainer can't create /dev destination automatically without overlay or underlay
FATAL:   container creation failed: mount hook function failure: mount /dev->/dev error: while mounting /dev: destination /dev doesn't exist in container

<amartinez/sashimi -v /c4/home/amartinez/sashimi:/c4/home/amartinez/sashimi docker://guigolab/ggsashimi /c4/home/amartinez/sashimi/ggsashimi.py -b sashimi_try2.tsv -c chr12:25358180-25403870 -g $f   
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: By using --writable, Apptainer can't create /dev destination automatically without overlay or underlay
FATAL:   container creation failed: mount hook function failure: mount /dev->/dev error: while mounting /dev: destination /dev doesn't exist in container


[amartinez@c4-n4:job=1475857 sashimi]$ /c4/home/amartinez/sashimi/ggsashimi.py -b sashimi_try2.tsv -c chr12:25358180-25403870 -g $f
Traceback (most recent call last):
  File "/c4/home/amartinez/sashimi/ggsashimi.py", line 8, in <module>
    import pysam
ImportError: No module named pysam

**Comment by amberdeja** [comment]
Hello Emilio,

Sorry to email again, but it would be really useful for our research to be able to map the gene with ggsashimi. Could you help me figure out why the script is not running?

Thank you,
Alejandra
________________________________
